name: Modeling And Simulation Lab
title: MnS | 3 Words
description: One or Two Sentences
tags:
  - Modeling
  - Simulation
  - Data Analytics
  - Artificial Intelligence
  - Reinforcement Learning
show_hero: true
menu:
  - title: Home
    url: /
  - title: AboutUs
    url: /about
  - title: People
    url: /people
  - title: Projects
    url: /
  - title: Publications
    url: /publications
  - title: Contact Us
    url: /contact
email: simon.anderson.tech@gmail.com
# See: https://disqus.com/
disqus_username: nonamed
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: https://formspree.io/f/xleaynll
paginate: 15
